#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

# Set conter to zero
counter=0

# While loop
while [ $counter -lt 10 ]; do
    echo "Best School"
    ((counter++))
done
