#!/usr/bin/env bash
# Prints "best school" 10 times except for 4 and 8 terations

# initialize counter
counter=1

# loop
while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
